import { UserRole } from "./roles";

export type Permission = 
  | 'VIEW_SIMULATIONS' | 'VIEW_PPV_MEDIA' | 'VIEW_LIVE_FEED'
  | 'VIEW_ANALYST_DATA' | 'REQUEST_COVERAGE' | 'CONTROL_DRONE'
  | 'CONTROL_CAMERA' | 'TRANSMIT_RANGER_ANALYST' | 'TRANSMIT_VISITOR_OPS'
  | 'OPS_OVERRIDE' | 'DEPLOY_UNITS' | 'BLACKLIST_AREAS' | 'VIEW_BODYCAM';

const ROLE_PERMISSIONS: Record<UserRole | 'guest', Permission[]> = {
  guest: ['VIEW_SIMULATIONS'],
  visitor_free: ['VIEW_SIMULATIONS', 'VIEW_PPV_MEDIA'],
  visitor_paid: ['VIEW_SIMULATIONS', 'VIEW_PPV_MEDIA', 'VIEW_LIVE_FEED', 'VIEW_ANALYST_DATA'],
  analyst: ['VIEW_LIVE_FEED', 'VIEW_ANALYST_DATA', 'REQUEST_COVERAGE', 'CONTROL_CAMERA', 'TRANSMIT_RANGER_ANALYST'],
  ranger: ['VIEW_LIVE_FEED', 'CONTROL_DRONE', 'CONTROL_CAMERA', 'TRANSMIT_RANGER_ANALYST', 'REQUEST_COVERAGE', 'VIEW_BODYCAM'],
  ops: [
    'VIEW_SIMULATIONS', 'VIEW_PPV_MEDIA', 'VIEW_LIVE_FEED', 'VIEW_ANALYST_DATA',
    'REQUEST_COVERAGE', 'CONTROL_DRONE', 'CONTROL_CAMERA', 'TRANSMIT_RANGER_ANALYST',
    'TRANSMIT_VISITOR_OPS', 'OPS_OVERRIDE', 'DEPLOY_UNITS', 'BLACKLIST_AREAS', 'VIEW_BODYCAM'
  ],
};

export const hasPermission = (role: UserRole | 'guest', permission: Permission): boolean => {
  return ROLE_PERMISSIONS[role].includes(permission);
};